[Register]

author = Dr. Bret Addison
description = Move the focused window using fixed or custom KWin layouts. Click the icon to open the layout sub-dock; middle-click to configure layouts.
category = 4
version = 1.3.0
title = Window Layouts
icon =
multi-instance = false
