#0.3.0

#[gtk-about]
[Icon]

#j+[0;128] Desired icon size for this applet
icon size = 0;0

#s Name of the icon as it will appear in the dock
name = Window Layouts

#g+ Image's filename
icon =

#d Name of the dock it belongs to
dock name =

order =

#[gtk-convert]
[Desklet]

#j+[48;512] Desklet dimensions
size = 164;96

#i[-2048;2048] Desklet horizontal position
x position = 0

#i[-2048;2048] Desklet vertical position
y position = 0

#b Is detached from the dock?
initially detached = false

#l[Normal;Keep above;Keep below;On Widget Layer;Reserve space] Accessibility
accessibility = 0

#b Should be visible on all desktops?
sticky = true

#b Lock the desklet position?
locked = false

#I[-180;180] Rotation
rotation = 0

use size =

#F[Decorations;gtk-orientation-portrait]
frame_deco =

#o+ Decoration theme
decorations = default

#[gtk-preferences]
[Configuration]
